# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.CharField(max_length=64, verbose_name='Author name'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
